config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :comments, only: [:create, :destroy]
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true

  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [ :user, :admin ]
  gravtastic default: :identicon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @comment = Comment.new(comment_params)
    authorize @comment
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(comment_params['post_id']) }
      else
        format.html { render :back }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize @comment
    @comment.destroy
    redirect_to :back
  end

  private

  def comment_params
    attributes = params.require(:comment).permit(:body, :post_id)
    attributes.merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    authorize @posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
    authorize @post
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    authorize @post
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      authorize @post
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dracks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class='background'>
    <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
    	<div class='container'>
				<%= link_to 'Dracks', root_path, class: 'navbar-brand'  %>
				<ul class="nav navbar-nav">
					<li class="nav-item">
						<%= link_to 'Blog', posts_path, class: 'nav-link'  %>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="https://www.youtube.com/channel/UCj_Tfkon3cVp_rc3w6zemkw">Youtube</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="https://www.twitch.tv/dr4ck5">Twitch</a>
					</li>
				</ul>
				<ul class="nav navbar-nav pull-xs-right">
					<% if user_signed_in? %>
						<li class="nav-item">
					  	<%= link_to 'Profile', edit_user_registration_path, class: 'nav-link' %>
					  </li>
					  <li class="nav-item">
					  	<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link'  %>        
					  </li>
					<% else %>
					  <li class="nav-item">
					  	<%= link_to 'Login', new_user_session_path, class: 'nav-link'  %>  
					  </li>
					<% end %>
				</ul>
  		</div>
    </nav>
    <div class='container foreground'>
    	<%= yield %>
	</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :desciption %>
    <div>
      <%= f.text_area :description, rows: 3, cols: 120 %>
    </div>
  </div>

  <div class="field">
    <%= f.text_area :body, class: "tinymce", rows: 18, cols: 120 %>
    <%= tinymce %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class: 'btn btn-link' %> |
<%= link_to 'Back', posts_path, class: 'btn btn-link' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% if policy(:post).new? %>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-link' %>
<% end %>

  <% @posts.each do |post| %>
  <div class="media">
    <h4 class="media-heading">
      <% if policy(post).show? %>
        <%= link_to post.title, post %>
      <% end %>
    </h4>
    <div class="media-body">
      <%= post.description %>
      <div>
        <% if policy(post).edit? %> 
          <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-link' %>
        <% end %>
        <% if policy(post).destroy? %>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: 'btn btn-link' %>

app/views/posts/show.html.erb
<h1>
  <%= @post.title %>
</h1>

<p>
  <%= @post.body.html_safe %>
</p>
<% if policy(@post).edit? %>
  <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-link' %> |
<% end %>
<%= link_to 'Back', posts_path, class: 'btn btn-link' %>

<%= form_for @comment do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>

  <div class="field">
    <%= f.label :body %>
    <div>
      <%= f.text_area :body, rows: 3, cols: 120 %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% @post.comments.each do |comment| %>
  <div class="media">
    <div class="media-left">
      <%= image_tag comment.user.gravatar_url, class: 'media-object' %>
    </div>
    <div class="media-body">
      <%= comment.body %>
    </div>
    <div class='media-right'>
      <% if policy(comment).destroy? %>
        <%= link_to comment_url(comment), class: 'btn btn-link', method: :delete do %>
          <%= fa_icon "trash" %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>